---
title: "LinearDiscriminantAnalysis-LDA"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

We try to test linear discvriminant analysis using our own generated data. We will have two data sets with labels A and B with different means and common variance.

```{r cars}


```

## Including Plots

You can also embed plots, for example:

```{r, echo=FALSE}

getTransformMatrix <- function(covMat)
{
  svdRes <- svd(covMat)
  
  U <- svdRes$u
  D <- diag(svdRes$d)
  V <- svdRes$v
  A = U %*% (D^0.5)
  A
}


#--------------------  generate data --------------------------------#

vars1      <- c(10, 5)
vars2      <- c(4, 4)
#correlMat
correlMat1 <- rbind(c(1, 0.6),
                   c(0.6, 1))

correlMat2 <- rbind(c(1, -0.6),
                   c(-0.6, 1))


covMat1   <- diag(vars1) %*% correlMat1 %*% diag(vars1)
covMat2   <-  diag(vars2) %*% correlMat2 %*% diag(vars2)

MU1       <- matrix(c(1,3), ncol=1)
MU2       <- matrix(c(10,10), ncol=1)


N1 <- 300
N2 <- 300

getData <- function(N, MU, covMat)
{
  e <- matrix(rnorm(2*N), nrow = 2)
  matrix(MU, ncol = N, nrow=2) + getTransformMatrix(covMat) %*% matrix(rnorm(2*N), nrow = 2)
}

#generate data points  for each distribution
#1. Random Normals
e <- matrix(rnorm(2*N1), nrow = 2)
#Data for fist set
D1 <- getData(N = N1, MU = MU1, covMat = covMat1)
D2 <- getData(N = N2, MU = MU2, covMat = covMat2)

dat_1 <- data.frame(x = D1[1,], y = D1[2,], "type" = "1")
dat_2 <- data.frame(x = D2[1,], y = D2[2,], "type" = "2")

bindedDat <- rbind(dat_1, dat_2)

bindedDat[["categ"]] = bindedDat$type == 1


#--------------------  generate data --------------------------------#



library(ggplot2)
ggplot(bindedDat, aes(x=x, y=y, color=type)) + geom_point(shape=1) + 
  geom_smooth(method=lm,   # Add linear regression lines
              se=FALSE)    # Don't add shaded confidence region

```

#Logistic Regression

```{r}
library(caTools)
set.seed(101) 
sample = sample.split(bindedDat$categ, SplitRatio = .75)
train = subset(bindedDat, sample == TRUE)
test  = subset(bindedDat, sample == FALSE)

table(train$categ)
table(test$categ)


logistic.fit = glm(categ ~ x + y, data = train, family = binomial)
summary(logistic.fit)
```

```{r}
fitted.results <- predict(logistic.fit, newdata=test, type='response')
#fitted.results

t <- table(fitted.results > 0.5, test$categ == 1)
#Accuracy
sum(diag(t))/sum(t)
```

```{r}
library(ROCR)
p   <- predict(logistic.fit, newdata=test, type="response")
pr  <- prediction(p, test$categ)
prf <- performance(pr, measure = "tpr", x.measure = "fpr")
plot(prf)

auc <- performance(pr, measure = "auc")
auc <- auc@y.values[[1]]
auc
```




## Linear Discriminant Analysis

```{r}
library(MASS)
lda.fit = lda(categ ~ x + y ,data=train)
lda.fit

lda.pred=predict (lda.fit , test)
pr  <- prediction(lda.pred$posterior[,"TRUE"], test$categ)
prf <- performance(pr, measure = "tpr", x.measure = "fpr")
plot(prf)

auc <- performance(pr, measure = "auc")
auc <- auc@y.values[[1]]
auc

```


# Quadratic Discriminant Analysis

```{r}
qda.fit = qda(categ ~ x + y , data=train)
qda.pred=predict (qda.fit , test)
pr  <- prediction(qda.pred$posterior[,"TRUE"], test$categ)
prf <- performance(pr, measure = "tpr", x.measure = "fpr")
plot(prf)

auc <- performance(pr, measure = "auc")
auc <- auc@y.values[[1]]
auc
```


# Boundaries : Logistic, LDA, QDA

```{r}
x <- seq(from = -30, to = +30, by = 1)
y <- seq(from = -15, to = 30,  by = 1)

vals          <- expand.grid(x,y)
colnames(vals) = c("x", "y")
#head(vals)


#QDA
vals_qda <- vals; 
qda.pred.grid = predict (qda.fit , vals_qda)
vals_qda[["type"]] = ifelse(qda.pred.grid$posterior[,2] >= 0.5, "1-grid", "2-grid")

#LDA
vals_lda <- vals
qda.pred.grid = predict (lda.fit , vals_lda)
vals_lda[["type"]] = ifelse(qda.pred.grid$posterior[,2] >= 0.5, "1-grid", "2-grid")

#Logistic
vals_logistic <- vals
logistic.pred.grid = predict(logistic.fit, newdata=vals_logistic, type='response')
vals_logistic[["type"]] = ifelse(logistic.pred.grid  >= 0.5, "1-grid", "2-grid")


ggplot( rbind( bindedDat[,c("x", "y", "type")],
               vals_logistic), aes(x=x, y=y, color=type)) + geom_point(shape=1)  + ggtitle("Logistic")

ggplot( rbind( bindedDat[,c("x", "y", "type")],
               vals_lda), aes(x=x, y=y, color=type)) + geom_point(shape=1)  + ggtitle("LDA")

ggplot( rbind( bindedDat[,c("x", "y", "type")],
               vals_qda), aes(x=x, y=y, color=type)) + geom_point(shape=1)  + ggtitle("QDA")


```










